sudo: required
services:
    - docker

before_install:
    - docker build -t czerwonykalafior/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run czerwonykalafior/react-test npm test -- --coverage

after_success:
    - docker build -t czerwonykalafior/multi-client ./client
    - docker build -t czerwonykalafior/multi-nginx ./nginx
    - docker build -t czerwonykalafior/multi-server ./server
    - docker build -t czerwonykalafior/multi-worker ./worker
    - echo "$docker_pass" | docker login -u "$docker_id" --password-stdin
    - docker push czerwonykalafior/multi-client 
    - docker push czerwonykalafior/multi-nginx 
    - docker push czerwonykalafior/multi-server 
    - docker push czerwonykalafior/multi-worker 